#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 61485-web-01 18.234.192.184:80 check
    server 61485-web-02 	54.164.213.35:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
